name: Invictus API

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      
      - name: Checkout code
        uses: actions/checkout@v4

      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      
      - name: Install Newman
        run: npm install -g newman

      
      - name: Install Newman Reporter HtmlExtra
        run: npm install -g newman-reporter-htmlextra

      
      - name: Check versions of Newman and Node
        run: |
          newman --version
          node --version

      
      - name: Execute Postman collection
        run: |
          newman run ./invictus.postman_collection.json \
            -e ./Invictus.postman_environment.json \
            -g ./workspace.postman_globals.json \
            -r htmlextra \
            --reporter-htmlextra-export ./report.html

      
      - name: Archive production artifacts
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: report
          path: ./report.html

 